### ISSUE TITLE
Sample program in README.md fails at print_pem method

### ISSUE THREAD

**Issue by roopahc** [kurtbrose/pyjks#11]
Error at line : print "\r\n".join(textwrap.wrap(base64.b64encode(data), 64))
                    TypeError: a bytes-like object is required, not 'dict'

**Comment by voetsjoeba** [comment]
What version of Python are you running?

**Comment by roopahc** [comment]
python 3.5

**Comment by voetsjoeba** [comment]
Indeed, I was about to ask whether you hadn't already have had to make changes to get it to run on Python 3 in the first place. In any case, to my view the main purpose of that sample code is to communicate example usage of the module, not so much a 100% Works Anywhere Guarantee™.

I am by no means an expert on Python 3's differences from 2, but there's already a pull request to implement some fixes from Python 3 (cfr. #8). The comments on that PR have some discussion that might be relevant to this case also, so maybe it's best I leave this to @doublereedkurt.

**Comment by mahmoud** [comment]
Congrats! You just found your first Python bug, of sorts.

Passing a bytes object into textwrap gives me the error:
```
>>> textwrap.wrap(b'test, 64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/textwrap.py", line 365, in wrap
    return w.wrap(text)
  File "/usr/lib/python3.4/textwrap.py", line 337, in wrap
    chunks = self._split_chunks(text)
  File "/usr/lib/python3.4/textwrap.py", line 323, in _split_chunks
    text = self._munge_whitespace(text)
  File "/usr/lib/python3.4/textwrap.py", line 142, in _munge_whitespace
    text = text.translate(self.unicode_whitespace_trans)
TypeError: 'dict' does not support the buffer interface
```
I believe this is masking the real error, which is that textwrap expects a Python 3 `str` object (aka a `unicode` or "text" object). `b64encode` returns `bytes`, so we have to `.decode('ascii')`, pass to `textwrap.wrap`, and continue from there.

**Comment by voetsjoeba** [comment]
@mahmoud is entirely correct, and his proposed fix works in Python2 as well, so here's a PR to make it happen.

**Comment by mahmoud** [comment]
Looks like this got fixed a while back. Closing this, thanks again!
