### ISSUE TITLE
javaobj blocks 2.6 backwards compat

### ISSUE THREAD

**Issue by mahmoud** [kurtbrose/pyjks#23]
Lately I've been working on docs and testing, and in adding tox I discovered the extent of our backwards incompatibility. As of now, I've got pyjks locally python2.6 syntax-compatible (and will commit the changes shortly), but I discovered that javaobj is Python 2.7+ only. 

Given the relatively small extent of javaobj usage last I checked, we had discussed maybe switching to a simpler dependency, even an internal util, that covered just the cases we needed.

Other options include making javaobj 2.6 compatible, or (the easiest) making pyjks 2.7+ only.

**Comment by voetsjoeba** [comment]
I'd prefer to try and make javaobj-py3 2.6-compatible, because I know there are people still stuck on Python 2.6 (RHEL6 is a common case) . I had a quick look and it seems like it should be just a couple of lines that need a syntax change, will submit a PR soon.

**Comment by mahmoud** [comment]
@voetsjoeba thank you for looking at this. I, too, know some folks stuck on 2.6. Time has really gotten away from me lately, but I'll be here to review + merge + rerelease. :)

**Comment by mahmoud** [comment]
For the moment it seems javaobj-py3 is actually 2.6 backward-compatible, at least for our test suite. I tested versions 0.2.1 (released in 2016) and 0.2.4 (released Jan 2018), both passed the suite fine. So, thanks as usual @voetsjoeba, looks like whatever you submitted did the trick! :)
