### ISSUE TITLE
Support for Keystore manipulation

### ISSUE THREAD

**Issue by dpeger** [kurtbrose/pyjks#27]
Does pyjks currently support importing keys or certificates into a JKS keystore or creation of a new keystore? If no, are there plans to implement something like this?

Best regards

**Comment by voetsjoeba** [comment]
Not at the moment, though we've considered it in the past. I imagine it should be feasible to do; the algorithms and store formats are well understood. Perhaps the only stumbling block could be emitting a serialized Java object for JCEKS keystores with SecretKey values, which would need support from [javaobj-py3](https://github.com/tcalmant/python-javaobj), though that could perhaps be left unimplemented until available.
