### ISSUE TITLE
Pyjks doesn't convert alias to lowercase

### ISSUE THREAD

**Issue by silvervesi** [kurtbrose/pyjks#38]
This is what Java Keytool does when importing items, although it's not documented everywhere. Keytool throws an error and Keystore Explorer fails silently when opening a keystore that has an alias where atleast one character is uppercase.

**Comment by mahmoud** [comment]
Oh, good catch, thank you! This is kind of unfortunate, as it's not documented and not strictly a format issue. Still, compatibility is the name of the game.

Sounds like it might be a small change. Since you have the setup to test, would you be able to issue a PR?

**Comment by silvervesi** [comment]
I'm on it.

Sv.

**Comment by silvervesi** [comment]
https://github.com/kurtbrose/pyjks/pull/39

Apologies if I have overlooked something obvious. The 2 tests there are
literally the first tests I've ever written.

Sv.

**Comment by kurtbrose** [comment]
thanks!  :-)

**Comment by mahmoud** [comment]
#39 fixes this and was released today in v18.0.0. Thanks all!
