### ISSUE TITLE
can not handle PKCS12 types of keystores

### ISSUE THREAD

**Issue by hlovdahl** [kurtbrose/pyjks#49]
I was trying to open a keystore that was in the PKCS12 format. This did not work, the error message was:
jks.util.BadKeystoreFormatException: Not a JKS or JCEKS keystore (magic number wrong; expected FEEDFEED or CECECECE)

P.S.
The problem started after I followed an advice that the keytool command gave:
Warning:
Nyckellagret JKS använder ett proprietärt format. Du bör migrera till PKCS12, som är ett branschstandardformat, med "keytool -importkeystore -srckeystore xxx.jks -destkeystore xxx.jks -deststoretype pkcs12".

It told me to convert the keystore to use the PKCS12 format.
D.S.

**Comment by mahmoud** [comment]
Interesting that keytool issues that warning. It's literally telling you not to use JKS (which is fine advice, even the creators of pyjks only used it for legacy integration). 

So, what's happened here is you've created a PKCS12 file with a `.jks` extension. PKCS12 stores typically end with a `.p12` extension, but keytool doesn't enforce that. 

But yeah, in summary, pyjks is working as expected, throwing an error on a non-JKS format file. `keytool`'s advice is not bad, but it'll be up to you and another library to follow it! :)
