### ISSUE TITLE
Misnamed variable in code example on PyPI

### ISSUE THREAD

**Issue by NicolasAgra** [kurtbrose/pyjks#52]
Maybe is not here the place but there is a little mismatch in the example site:

![image](https://user-images.githubusercontent.com/33065414/63557118-bc933c00-c51d-11e9-8757-bdcb97df45dd.png)

**Comment by mahmoud** [comment]
Good point! I'll get that fixed in the next release :)

**Comment by mahmoud** [comment]
20.0.0 published today, so PyPI is hopefully correct. Thanks again!
