### ISSUE TITLE
Jceks File Not Supporting in Python 2.7.5

### ISSUE THREAD

**Issue by varun414** [kurtbrose/pyjks#60]
I am getting below error though we have jks version 19.0.0 and javaobj = 0.4.0.Does any one face this problem while calling jks.KeyStore.load(), though I am giving correct  store password
cc: @danpker @cory-parr

Python 2.7.5 
Type "help", "copyright", "credits" or "license" for more information.
>>> import jks
>>> jks.KeyStore.load('file_name.jceks',"pass_phrase")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/jks/util.py", line 92, in load
    try_decrypt_keys=try_decrypt_keys)
  File "/usr/lib/python2.7/site-packages/jks/jks.py", line 525, in loads
    entry.decrypt(store_password)
  File "/usr/lib/python2.7/site-packages/jks/jks.py", line 320, in decrypt
    raise UnexpectedAlgorithmException("Unexpected algorithm used for encrypting SealedObject: sealAlg=%s" % sealed_obj.sealAlg)
jks.util.UnexpectedAlgorithmException: Unexpected algorithm used for encrypting SealedObject: sealAlg=PBEWithMD5AndTripleDES

**Comment by varun414** [comment]
@mahmoud
FYI Can you help me out.

**Comment by mahmoud** [comment]
That's a bit bizarre, given this line: https://github.com/kurtbrose/pyjks/blob/629742006ee24477d7c649b279b43e054f46b088/jks/jks.py#L303

Seems like it'd have you covered.

If I were you, I'd do a `pdb.post_mortem()` or run with `python -m pdb` and find out why that string is not comparing as equal. Maybe something to do with a library version? Post a `pip freeze` just in case.

**Comment by kuldeep-mishra** [comment]
@mahmoud 

I've just modified below code in **jks.py** to typecast <class 'javaobj.v1.beans.JavaString'> to <type 'str'>.

```
<         if sealed_obj.sealAlg == "PBEWithMD5AndTripleDES":
---
>         if str(sealed_obj.sealAlg) == "PBEWithMD5AndTripleDES":
```
Previously:
type of sealed_obj.sealAlg =<class 'javaobj.v1.beans.JavaString'>
after change:
type of sealed_obj.sealAlg =<type 'str'>

Modified code is compatible python3 as well.

Is this modification acceptable?

**Comment by varun414** [comment]
@mahmoud can you closed this seems jira 61 have solutions and commit also

**Comment by mahmoud** [comment]
Sure, sounds good. Thanks!
